商品情報編集機能
kurimaru2000/furima-34822-2 pull request #6
Opened 2021-03-30 23:51 UTC by kurimaru2000

# What
商品情報編集機能の実装

# Why
商品情報編集機能の実装のため

2021-03-30 23:52 UTC, kurimaru2000 commented
お世話になります。
コードをプッシュしました。
コードレビューをお願いします。
		ログイン状態の出品者は、商品情報編集ページに遷移できる動画
		https://gyazo.com/b69cfc8700130821cd47be339bb11db8
		正しく情報を記入すると、商品の情報を編集できる動画
		https://gyazo.com/b2dcfe1acd69a416c2755d64634279bd
		入力に問題のある状態では商品の情報は編集できず、エラーメッセージが出力される動画
		https://gyazo.com/d3db41d92c653f6293bcbd2fbce0ac18
		何も編集せずに更新をしても画像無しの商品にならない動画
		https://gyazo.com/4c59b4510454a339ff0d79c2ee8a3d0d
		ログアウト状態のユーザーは、URLを直接入力して商品情報編集ページへ遷移しようとすると、ログインページに遷移する動画
		https://gyazo.com/eb4d45db3d256bd6611227094b91891c
		商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示される動画（画像に関しては、表示されない状態で良い）
		https://gyazo.com/7d18eb78713a0a30834756e25d65fc04

2021-03-31 01:28 UTC, maimai0401 requested changes
レビュー依頼ありがとうございます。
２点コメントいたしましたので、ご確認をお願いいたします。
修正後、再度レビュー依頼フォームにてご提出くださいませ。

2021-03-31 01:28 UTC, maimai0401 commented on app/controllers/products_controller.rb
> +  before_action :authenticate_user!, only: [:new, :edit, :destroy]
こちらの記述はupdateアクションにも適用されるように実装しましょう。 検証ツールなどを用いてリクエストを改ざんすることで、編集画面を経由せずにupdateアクションを動かすことが可能です。 そういった行為への対策として、updateアクションにもeditアクションと同様の条件分岐を加えることが必要となります。

2021-03-31 01:28 UTC, maimai0401 commented on app/controllers/products_controller.rb
> +    unless @product.user_id == current_user.id
```
 unless @product.user_id == current_user.id
      redirect_to action: :index
    end
```
updateアクションにも「出品者のみが編集できる」条件分岐を実装しましょう。 適応させる理由としてコードの保守性を高めるためです。 (ブラウザの検証ツールを用いると 更新ボタンを作成できてしまいます。不正なユーザーが操作できないようサーバー側でも対応させましょう。)

2021-03-31 01:49 UTC, kurimaru2000 commented
訂正コードをプッシュしました。
コードレビューをお願いします。

2021-03-31 02:00 UTC, sgwr-0113 reviewed
レビュー依頼ありがとうございます！
コメントのご確認をお願いします。

修正後、再度フォームにてレビュー依頼をお願いいたします。

2021-03-31 02:00 UTC, sgwr-0113 commented on app/controllers/products_controller.rb
> +    @product = Product.find(params[:id])
```rb
@product = Product.find(params[:id])
```

こちらの記述は**show, edit, updateアクション内で共通の記述です。**
可読性の観点からメソッドを別に定義し、`before_action`を用いて各アクションに適用させましょう！

2021-03-31 02:00 UTC, sgwr-0113 commented on app/controllers/products_controller.rb
> +  before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
```
before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
```

`:destroy`については削除するかコメントアウトしておきましょう！
（商品削除機能のプルリクエストで差分に上がらなくなってしまうため）

2021-03-31 02:00 UTC, sgwr-0113 commented on app/controllers/products_controller.rb
> +      end
```rb
unless @product.user_id == current_user.id
    redirect_to action: :index
  else
    @product.update(product_params)
      if @product.update(product_params)
           redirect_to product_path(@product.id), method: :get
      else
        render :edit
      end
  end
```

こちらは条件分岐を2重にせず、

```rb
redirect_to action: :index unless @product.user_id == current_user.id

if @product.update(product_params)
     redirect_to product_path(@product.id), method: :get
else
  render :edit
end
```

とすることで、可読性の高い記述になります。

また、トップページへ遷移させる`redirect_to action: :index`の部分は**edit, update共通の記述**であるため、`before_action`を用いて1つにまとめておきましょう！

2021-03-31 02:42 UTC, masayaomoto reviewed
レビュー依頼ありがとうございます！
修正点確認させていただきました。
追加でコメントいたしましたので、ご確認お願いします！

2021-03-31 02:42 UTC, masayaomoto commented on app/controllers/products_controller.rb
> +    @product.update(product_params)
```ruby
@product.update(product_params)
```
こちらの記述は削除しましょう。
33行目にて更新処理を行うためです。

2021-03-31 02:42 UTC, masayaomoto commented on app/controllers/products_controller.rb
> +    redirect_to action: :indec unless @product.user_id == current_user.id
25 ~ 27 行目
```ruby
    unless @product.user_id == current_user.id
      redirect_to action: :index
    end
```
32行目
```ruby
    redirect_to action: :indec unless @product.user_id == current_user.id
```
上記二つの条件は
出品者でなければトップページへとリダイレクトさせるという同じ条件になっております。
メソッドとして定義しbeforeアクションで呼び出すことにより
重複した内容の記述を省略でき記述量の削減ができます。
修正しましょう。

2021-03-31 02:42 UTC, masayaomoto commented on app/views/products/show.html.erb
> +            <%= link_to "削除", product_path, method: :delete, class:"item-destroy" %>
```ruby
<%= link_to "削除", product_path, method: :delete, class:"item-destroy" %>
```
上記修正箇所も削除機能の実装範囲となりますので現状ではコメントアウトをお願いいたします。

2021-03-31 02:48 UTC, kurimaru2000 commented
訂正コードをプッシュしました。
コードレビューをお願いします。

2021-03-31 02:51 UTC, maimai0401 reviewed
レビュー依頼ありがとうございます。
LGTMとさせていただきます！実装お疲れ様でした。

マージ後、ローカルのmasterブランチに忘れずにプルしましょう。
その後、新しいブランチを作成し次の実装に取り組んでいただけますと幸いです。
引き続き実装頑張っていきましょう！

2021-03-31 02:53 UTC, merged